### ISSUE TITLE
Case sensitivity #include "Arduino.h"

### ISSUE THREAD

**Issue by schlasim** [luisllamasbinaburo/Arduino-I2CScanner#1]
I think the A in  #include "Arduino.h" should be an uppercase letter. In my case I had to change this, to make the code compile.

**Comment by luisllamasbinaburo** [comment]
Ok, maybe it's a Arduino IDE behavior (I never use Arduino IDE). Anyway, I fixed. Thanks!

**Comment by schlasim** [comment]
Thank you!
